### ISSUE TITLE
Better visualisation with files grouped by directories

### ISSUE THREAD

**Issue by benwinding** [PSeitz/ts-dependency-graph#11]
Love the tool, very impressive.

Instead of seeing every file as a complete path from the root (below each file has entire path).
![image](https://user-images.githubusercontent.com/11782590/162675720-30bba0a5-bd6d-4c28-831a-718c6ad74fd8.png)

You could group them by directories, like the way [depcruise](https://github.com/sverweij/dependency-cruiser) displays it.
![image](https://user-images.githubusercontent.com/11782590/162675634-37f787c7-c17d-4b82-a6ba-bc239239500e.png)

Your tool has much better information about the dependencies links though 👌

**Comment by PSeitz** [comment]
Thanks for the suggestion, cool that you like the tool.
I added the functionality, you can see an example here:
https://github.com/PSeitz/ts-dependency-graph#use-from-github-repo

**Comment by PSeitz** [comment]
Released with `1.3.0`

**Comment by benwinding** [comment]
Wow! That's exactly what we wanted! 👌 
Thanks so much @PSeitz  ❤️
