### ISSUE TITLE
There is no support for compilerOptions paths

### ISSUE THREAD

**Issue by olek-wizzdev** [PSeitz/ts-dependency-graph#17]
In project I'm working on we have tsfonfig: 

```json
{
	"compilerOptions": {
		"paths": {
			"@/*": ["src/*"],
		}
	}
}
```

Would it be possible to add support for mappings like that?

**Comment by PSeitz** [comment]
I added some support for path mappings recently, although it may not yet cover all cases https://github.com/PSeitz/ts-dependency-graph/commit/a6a6e69422d9db09b9302548b26e511419902211

Are you using version 1.4?

**Comment by oleks12345** [comment]
I think I'm using newest, i used it with npx

**Comment by PSeitz** [comment]
Can you provide a minimal example?

**Comment by literatura** [comment]
Same problem. I am using version 1.4.1. 
tsconfig.json
```
"compilerOptions": {
    "noEmit": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "target": "es6",
    "lib": ["ES2021", "DOM"],
    "strict": true,
    "types": ["jest", "cypress", "node", "cypress-real-events", "cypress-wait-until"],
    "baseUrl": "./",
    "paths": {
      "@cy/*": ["cypress/*"],
      "@src/*": ["src/*"],
      "@config": ["config"]
    }
  },
  "include": ["src/**/*.ts", "cypress/support/index.ts", "*.ts"],
  "exclude": ["scripts"]
  ```

Start command `ts_dependency_graph --start ./cypress/screens/someScreen.screen.ts` from project root.

In file cypress/e2e/some/someSpec.cy.ts we have import `import { emailGalleryScreen } from '@cy/screens/gallery/emailGallery.screen'`

But we get an empty result:
`digraph graphname
{
}
`

The same if I do `ts_dependency_graph --start cypress/e2e/units/emailGalleryOverview.cy.ts`

**Comment by PSeitz** [comment]
Can you provide a small example with the config and some test files?

**Comment by literatura** [comment]
I created a small demo https://github.com/literatura/example. 

Try `ts_dependency_graph --start ./cypress/screens/email-documents/emailOverview.ts` or `ts_dependency_graph --start ./cypress/e2e/units/emailGalleryOverview.cy.ts`

**Comment by PSeitz** [comment]
Thanks, It seems my `prepublish` script wasn't executed for some reason, therefore the data on npm was outdated.
I published a new version, can you retry?

**Comment by literatura** [comment]
Thanks! I try in my demo and in project. 
1. `ts_dependency_graph --version` -> 1.4.3
2. `ts_dependency_graph --start ./cypress/screens/email-documents/emailOverview.ts` ->

> {
>     "cypress/screens/email-documents/emailOverview.ts" [shape=record , fillcolor=orange style=filled  label="cypress/screens/email-documents/emailOverview.ts"]
>     "cypress/components/index.ts" [shape=record  label="cypress/components/index.ts"]
>     subgraph Rel1 {
>         "cypress/screens/email-documents/emailOverview.ts" -> "cypress/components/index.ts" [color = "orange"]
>     }
> }

But I expect to see ./cypress/e2e/units/emailGalleryOverview.cy.ts in this list.

4. `ts_dependency_graph --start ./cypress/e2e/units/emailGalleryOverview.cy.ts ` -> empty graph

**Comment by PSeitz** [comment]
There was an error when constructing the path. Can you retry?

**Comment by literatura** [comment]
1. `ts_dependency_graph --version` -> 1.4.4
2. `ts_dependency_graph --start ./cypress/screens/email-documents/emailOverview.ts` ->

```
 {
    "cypress/screens/email-documents/emailOverview.ts" [shape=record , fillcolor=orange style=filled  label="cypress/screens/email-documents/emailOverview.ts"]
    "cypress/components/index.ts" [shape=record  label="cypress/components/index.ts"]
     subgraph Rel1 {
         "cypress/screens/email-documents/emailOverview.ts" -> "cypress/components/index.ts" [color = "orange"]
     }
 }
```

3. `ts_dependency_graph --start ./cypress/e2e/units/emailGalleryOverview.cy.ts `->
```
{
    "cypress/e2e/units/emailGalleryOverview.cy.ts" [shape=record , fillcolor=orange style=filled  label="cypress/e2e/units/emailGalleryOverview.cy.ts"]
    "cypress/screens/email-documents/emailOverview.ts" [shape=record  label="cypress/screens/email-documents/emailOverview.ts"]
    "cypress/components/index.ts" [shape=record  label="cypress/components/index.ts"]
    subgraph Rel1 {
        "cypress/e2e/units/emailGalleryOverview.cy.ts" -> "cypress/screens/email-documents/emailOverview.ts" [color = "orange"]
        "cypress/screens/email-documents/emailOverview.ts" -> "cypress/components/index.ts" [color = "#F744EF"]
    }
}
```
Thanks! It looks great!
It would be cool to build a graph in the other direction: show the files where the current file is used. Then in point 2 we would see the file cypress/e2e/units/emailGalleryOverview.cy.ts in the list. Something like` ts_dependency_graph --end`

But I think the current capabilities are enough to solve my problem. Thanks!

**Comment by PSeitz** [comment]
@olek-wizzdev @oleks12345 Can you retry?
