### ISSUE TITLE
Allow files with explicit .js suffix to be importet as .ts, if found

### ISSUE THREAD

**Issue by HaraldKi** [PSeitz/ts-dependency-graph#9]
In a small web project, I prefer not to use a package tool but only compile Typescript into Javascript. To not confuse web servers with requests for non-suffixed files, I use the explicit `.js` suffix in imports which the Typescript compiler happily maps to the respective `.ts.` file for import

I patched `ts_dependency_graph` accordingly and provide the patch attached. Let me know if you prefer a merge request, but since it is such a small change, the whole procedure with forking and so on seems overkill. (Sorry for the silly .txt suffix of the patch, .patch can't be uploaded :-)
[allow_js_suffix_imports.txt](https://github.com/PSeitz/ts-dependency-graph/files/8009955/allow_js_suffix_imports.txt)

Thanks for the nice tool btw.

**Comment by PSeitz** [comment]
Thanks for the diff, I applied it and pushed it to master.  I will soon release it. Sorry for the late response

**Comment by PSeitz** [comment]
Released with `1.3.0`
